[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_BACKEND_URL = "https://aibos-github-api.onrender.com"

[context.deploy-preview.environment]
  VITE_BACKEND_URL = "https://aibos-github-api.onrender.com"

[context.branch-deploy.environment]
  VITE_BACKEND_URL = "https://aibos-github-api.onrender.com"
